# Streamlit Dockerfile
FROM python:3.11
# Set the working directory
WORKDIR /app
# Copy the current directory contents into the container at/app
COPY . .
# Install the dependencies
RUN pip install streamlit requests numpy
# Expose the default Streamlit port
EXPOSE 8501
# Command to run the Streamlit app
CMD ["streamlit", "run", "./code/deployment/app/my_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0", "&"]