# Use an official Python runtime as a parent image
FROM python:3.11
# Set the working directory
WORKDIR /app
# Copy the current directory contents into the container at/app
COPY . .
# Install the necessary packages
RUN pip install fastapi uvicorn torch numpy
# Expose port 8000 to the outside world
EXPOSE 8000
WORKDIR ./code/deployment/api
# Run the FastAPI server
CMD ["uvicorn", "my_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]